/*
    THIS IS CONSTANTS FOR EVERY RESPONSE MESSAGES
    =============================================
    It can : 
    - reduces typo
    - not to write same purpose of response message with another content

    If want to add new response message, please add it below
*/

export const responseMessage = {

  // GENERAL --------------------------------------------------------
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  MISSING_REQUIRED_DATA: 'MISSING_REQUIRED_DATA',
  INVALID_REQUEST_DATA: 'INVALID_REQUEST_DATA',
  PRE_REGISTER_NEEDED: 'PRE_REGISTER_NEEDED',
  ACCOUNT_ALREADY_REGISTERED: 'ACCOUNT_ALREADY_REGISTERED',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  // AUTH -----------------------------------------------------------
  USER_FOUND: 'USER_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  AUTHENTICATION_NOT_FOUND: 'AUTHENTICATION_NOT_FOUND',
  USER_ALREADY_REGISTERED: 'USER_ALREADY_REGISTERED',
  NEW_USER_CREATED: 'NEW_USER_CREATED',
  ROLE_NO_FOUND: 'ROLE_NO_FOUND',
  REQUEST_BODY_INVALID: 'REQUEST_BODY_INVALID',
  INVALID_USERNAME_OR_PASSWORD: 'INVALID_USERNAME_OR_PASSWORD',
  MAXIMUM_INVOICE_AMOUNT_EXCEEDED: 'MAXIMUM_INVOICE_AMOUNT_EXCEEDED',
  MAXIMUM_PLAFOND_AMOUNT_EXCEEDED: 'MAXIMUM_PLAFOND_AMOUNT_EXCEEDED',
  INVALID_LOAN_ID: 'INVALID_LOAN_ID'
};
